name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
          use-cross: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/crow
