name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
          use-cross: true
      - name: compress
        run: tar -czf crow.tar.gz target/release/crow
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: crow.tar.gz
