name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
          use-cross: true
      - name: compress
        run: tar -C target/release -czf crow.tar.gz crow
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: crow.tar.gz
       - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          # Required, custom GitHub access token with the 'public_repo' and 'workflow' scopes
          token: ${{secrets.CROW_TAP_TOKEN}}
          # Optional, defaults to homebrew/core
          tap: sandstorm/crow
          # Formula name, required
          formula: crow
          # Optional, will be determined automatically
          tag: ${{github.ref}}
          # Optional, will be determined automatically
          revision: ${{github.sha}}
          # Optional, if don't want to check for already open PRs
          force: false # true         
